# Site settings
title: Letty Stott
tagline: By Matt Jolly
description: > # this means to ignore newlines until "baseurl:"
  Letty is one of the UK’s most exciting and versatile French horn players, performing classical and commercial music, in theatres, on ancient horns and in education settings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lettystott.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/sass
